export const degrees = [
    { key: "associate", label: "Associate" },
    { key: "bachelor", label: "Bachelor's, (BSc)" },
    { key: "master", label: "Master's (MSc)" },
    { key: "phd", label: "Post-Doctorate (Ph.D.)" },
    { key: "professional", label: "Professional (M.D., J.D.)" },
    { key: "other", label: "Other" },
]

export const languagesList = [
    { key: "af", label: "Afrikaans" },
    { key: "am", label: "Amharic" },
    { key: "ar", label: "Arabic" },
    { key: "bn", label: "Bengali" },
    { key: "bg", label: "Bulgarian" },
    { key: "my", label: "Burmese" },
    { key: "ca", label: "Catalan" },
    { key: "zh", label: "Mandarin Chinese" },
    { key: "hr", label: "Croatian" },
    { key: "cs", label: "Czech" },
    { key: "da", label: "Danish" },
    { key: "nl", label: "Dutch" },
    { key: "en", label: "English" },
    { key: "et", label: "Estonian" },
    { key: "fa", label: "Persian" },
    { key: "fi", label: "Finnish" },
    { key: "fr", label: "French" },
    { key: "ka", label: "Georgian" },
    { key: "de", label: "German" },
    { key: "el", label: "Greek" },
    { key: "gu", label: "Gujarati" },
    { key: "hi", label: "Hindi" },
    { key: "hu", label: "Hungarian" },
    { key: "is", label: "Icelandic" },
    { key: "id", label: "Indonesian" },
    { key: "it", label: "Italian" },
    { key: "ja", label: "Japanese" },
    { key: "jv", label: "Javanese" },
    { key: "kn", label: "Kannada" },
    { key: "ko", label: "Korean" },
    { key: "lv", label: "Latvian" },
    { key: "lt", label: "Lithuanian" },
    { key: "mr", label: "Marathi" },
    { key: "ms", label: "Malay" },
    { key: "pa", label: "Punjabi" },
    { key: "pl", label: "Polish" },
    { key: "pt", label: "Portuguese" },
    { key: "ro", label: "Romanian" },
    { key: "ru", label: "Russian" },
    { key: "sr", label: "Serbian" },
    { key: "es", label: "Spanish" },
    { key: "sv", label: "Swedish" },
    { key: "ta", label: "Tamil" },
    { key: "te", label: "Telugu" },
    { key: "th", label: "Thai" },
    { key: "tr", label: "Turkish" },
    { key: "ur", label: "Urdu" },
    { key: "vi", label: "Vietnamese" }
];

export const proficiencyLevels = [
    { key: "A1", label: "Beginner" },
    { key: "A2", label: "Elementary" },
    { key: "B1", label: "Intermediate" },
    { key: "B2", label: "Upper Intermediate" },
    { key: "C1", label: "Advanced" },
    { key: "C2", label: "Proficient" }
];

export const socialLinks = [
    { name: 'facebook', baseUrl: 'https://facebook.com/' },
    { name: 'instagram', baseUrl: 'https://instagram.com/' },
    { name: 'linkedin', baseUrl: 'https://linkedin.com/in/' },
    { name: 'tiktok', baseUrl: 'https://tiktok.com/@' },
    { name: 'youtube', baseUrl: 'https://youtube.com/@' },
    { name: 'github', baseUrl: 'https://github.com/' },
];
